# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"
run:
  tests: false

linters:
  default: standard # 包含 errorcheck, govet, ineffassign, staticcheck, structcheck, unused
  enable:
    - gocritic
    - canonicalheader
    - errorlint
    - perfsprint
    - modernize
    - revive
    - bodyclose
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - opinionated
      disabled-tags:
        - experimental
    revive:
      enable-default-rules: true
      rules:
        - name: unused-parameter
  exclusions:
    paths:
      - "copy"
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling

formatters:
  enable:
    - gci
    - gofumpt
    - golines
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(github.com/sanbei101/blue-card-engine)
    gofumpt:
      extra-rules: true
      module-path: "github.com/sanbei101/blue-card-engine"

    golines:
      max-len: 120
      shorten-comments: true
  exclusions:
    paths:
      - "copy"