edition = "2024";

package proto.cardengine.v1;

message TemplateItem {
  string id = 1;
  string name = 2;
  string kind = 3;
}

message TemplateListRequest {}

message TemplateListResponse {
  repeated TemplateItem templates = 1;
}

message CardItem {
  string id = 1;
  string name = 2;
  string url = 3;
}

message CardsListRequest {
  string title = 1;
  string keyword = 2;
  repeated string template_ids = 3;
}

message CardsListResponse {
  repeated CardItem templates = 1;
}

service CardEngineService {
  rpc TemplateList(TemplateListRequest) returns (TemplateListResponse) {}
  rpc CardsList(CardsListRequest) returns (CardsListResponse) {}
}
