import type { CardTemplate } from "@/types";

const baseBox = {
  x: 96,
  y: 250,
  width: 708,
  height: 620,
  minFontSize: 44,
  maxFontSize: 92,
  maxLines: 7,
  lineHeight: 1.26,
  align: "left" as const,
};

export const templates: CardTemplate[] = [
  {
    id: "question-blue",
    name: "清透问号",
    kind: "question",
    background: "#eef9fd",
    foreground: "#093c4a",
    accent: "#ffe23b",
    muted: "#9fd4e6",
    fontFamily: '"ZCOOL XiaoWei", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 800,
    radius: 54,
    textBox: { ...baseBox, y: 290, maxFontSize: 88, maxLines: 6 },
  },
  {
    id: "yellow-memo",
    name: "便签日记",
    kind: "memo",
    background: "#fff4a8",
    foreground: "#202018",
    accent: "#ff6b35",
    muted: "#d8b94f",
    fontFamily: '"Ma Shan Zheng", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 750,
    radius: 28,
    textBox: { ...baseBox, x: 90, y: 245, width: 720, maxFontSize: 82 },
  },
  {
    id: "editorial-black",
    name: "黑白杂志",
    kind: "editorial",
    background: "#f7f5ef",
    foreground: "#101010",
    accent: "#ef4136",
    muted: "#b6b1a8",
    fontFamily: '"ZCOOL KuaiLe", "Songti SC", "Noto Serif SC", serif',
    fontWeight: 800,
    radius: 0,
    textBox: {
      ...baseBox,
      x: 82,
      y: 280,
      width: 736,
      height: 630,
      minFontSize: 42,
      maxFontSize: 84,
      lineHeight: 1.2,
    },
  },
  {
    id: "lavender-soft",
    name: "柔雾紫",
    kind: "lavender",
    background: "#eee8ff",
    foreground: "#30245f",
    accent: "#8f68ff",
    muted: "#c7b9f5",
    fontFamily: '"Long Cang", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 760,
    radius: 72,
    textBox: {
      ...baseBox,
      x: 110,
      y: 300,
      width: 680,
      height: 550,
      maxFontSize: 80,
      align: "center",
    },
  },
  {
    id: "green-notebook",
    name: "绿格手账",
    kind: "notebook",
    background: "#e9f3df",
    foreground: "#23452e",
    accent: "#ff7a59",
    muted: "#a8c69c",
    fontFamily: '"ZCOOL QingKe HuangYou", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 760,
    radius: 42,
    textBox: {
      ...baseBox,
      x: 115,
      y: 280,
      width: 660,
      height: 590,
      minFontSize: 40,
      maxFontSize: 78,
      maxLines: 8,
    },
  },
  {
    id: "red-stamp",
    name: "红印宣言",
    kind: "stamp",
    background: "#fff0e7",
    foreground: "#7d201b",
    accent: "#e83a2f",
    muted: "#e0a298",
    fontFamily: '"Long Cang", "Songti SC", "Noto Serif SC", serif',
    fontWeight: 900,
    radius: 24,
    textBox: {
      ...baseBox,
      x: 92,
      y: 255,
      width: 716,
      height: 610,
      maxFontSize: 86,
      lineHeight: 1.18,
      align: "center",
    },
  },
  {
    id: "blue-grid",
    name: "蓝图网格",
    kind: "grid",
    background: "#eaf2ff",
    foreground: "#173f7a",
    accent: "#3978ff",
    muted: "#b8cff5",
    fontFamily: '"ZCOOL XiaoWei", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 780,
    radius: 40,
    textBox: {
      ...baseBox,
      x: 100,
      y: 300,
      width: 700,
      height: 580,
      maxFontSize: 80,
      maxLines: 7,
    },
  },
  {
    id: "midnight-stars",
    name: "深夜星光",
    kind: "night",
    background: "#11162a",
    foreground: "#f6f1d8",
    accent: "#ffcc4d",
    muted: "#6a7399",
    fontFamily: '"ZCOOL QingKe HuangYou", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 740,
    radius: 58,
    textBox: {
      ...baseBox,
      x: 110,
      y: 315,
      width: 680,
      height: 560,
      maxFontSize: 78,
      align: "center",
    },
  },
  {
    id: "orange-burst",
    name: "橙色爆炸",
    kind: "burst",
    background: "#ff8a42",
    foreground: "#2b1710",
    accent: "#fff3cf",
    muted: "#ffb07e",
    fontFamily: '"Ma Shan Zheng", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 900,
    radius: 46,
    textBox: {
      ...baseBox,
      x: 98,
      y: 285,
      width: 704,
      height: 590,
      maxFontSize: 86,
      lineHeight: 1.16,
      align: "center",
    },
  },
  {
    id: "beige-paper",
    name: "纸张摘录",
    kind: "paper",
    background: "#f0eadf",
    foreground: "#3a3128",
    accent: "#315d4f",
    muted: "#c9bead",
    fontFamily: '"Long Cang", "Songti SC", "Noto Serif SC", serif',
    fontWeight: 700,
    radius: 18,
    textBox: {
      ...baseBox,
      x: 120,
      y: 290,
      width: 660,
      height: 600,
      minFontSize: 40,
      maxFontSize: 76,
      lineHeight: 1.34,
    },
  },
  {
    id: "pink-bubble",
    name: "粉色气泡",
    kind: "bubble",
    background: "#ffe9f1",
    foreground: "#61253c",
    accent: "#ff5790",
    muted: "#efb7cb",
    fontFamily: '"Long Cang", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 790,
    radius: 76,
    textBox: {
      ...baseBox,
      x: 104,
      y: 315,
      width: 692,
      height: 540,
      maxFontSize: 80,
      align: "center",
    },
  },
  {
    id: "mono-frame",
    name: "极简边框",
    kind: "mono",
    background: "#ffffff",
    foreground: "#181818",
    accent: "#181818",
    muted: "#d9d9d9",
    fontFamily: '"ZCOOL KuaiLe", "PingFang SC", "Microsoft YaHei", sans-serif',
    fontWeight: 700,
    radius: 12,
    frame: "#181818",
    textBox: {
      ...baseBox,
      x: 110,
      y: 300,
      width: 680,
      height: 560,
      maxFontSize: 78,
      align: "center",
    },
  },
];
