name: Bench

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  bench:
    runs-on: ubuntu-latest
    env:
      GOEXPERIMENT: jsonv2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Run tests and benchmarks
        uses: sanbei101/go-bench-pprof-action@v1
        with:
          top: 20